### PR TITLE
Rotate hero image

### PR DESCRIPTION
**Pull request by Hoverbear**
I'm not sure if you're open to a new fluff for your readme, but Nami and I are paws-itively thrilled to see your cool project so far!

I also had to remove the image from the `src/lib.rs` since Rustdoc doesn't display it :(

She consents to you using this or any image of her image for this project!

### CODE REVIEW

**Comment by itsybitesyspider** [comment]
That is a very good dog!

This project uses `[cargo readme](https://github.com/livioribeiro/cargo-readme)` to copy the rustdoc in lib.rs to README.md, so this PR will not be durable as-is.

I've set up a github page (https://itsybitesyspider.github.io/retriever/) which I believe we should be able to hotlink to and see the doggo even through rustdoc. If you want to make this work, I will accept this PR.

I should also set up CI to catch the readme issue (./bin/ci works today, but you have to run it manually so it's not real CI).

**Comment by itsybitesyspider** [comment]
I don't suppose we could use one like [this](https://twitter.com/nami_num_nums/status/1194356172649725952)? I feel it's more friendly if Nami's looking into the camera.

**Comment by Hoverbear** [comment]
Oh I didn't know about `cargo readme`!

Thse should be done. :)

**Comment by Hoverbear** [comment]
Oh no the `README.md` is broken now. Q_Q

**Comment by Hoverbear** [comment]
You fixed it! :)

**Comment by itsybitesyspider** [comment]
My best guess is Github has some surprise URL replacement thing going on in the markdown rendering, which is itself also broken. Also your README was in "Little-endian UTF-16 Unicode text" which git brilliantly abstracts away into nothing, but I suspect it also broke GitHub Pages' rendering somehow (just in case it's ever relevant in the future).  ¯\_(ツ)_/¯

**Comment by Hoverbear** [comment]
I blame Windows. :(

**Pull request merged**
